### ISSUE TITLE
Assembly Binding with .Net 4.0 project

### ISSUE THREAD

**Issue by wookiesh** [TryStatsN/StatsN#5]
Hello, got a lot of warning issue but which somehow prevent the project to launch and even compile sometimes, did not yet really understand how though:

`Gravité	Code	Description	Projet	Rang de projet	Fichier	Ligne	État de la suppression
Avertissement		impossible de résoudre la référence primaire "Microsoft.Threading.Tasks.Extensions, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL", car elle a une dépendance indirecte sur l'assembly Framework "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" qui n'a pas été résolu dans le framework actuellement ciblé. ".NETFramework,Version=v4.0". Pour résoudre ce problème, supprimez la référence "Microsoft.Threading.Tasks.Extensions, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" ou reciblez votre application vers une version de framework qui contient "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".	Goodyear.DataAccess	1			
`
`Gravité	Code	Description	Projet	Rang de projet	Fichier	Ligne	État de la suppression
Avertissement		impossible de résoudre la référence primaire "StatsN, Version=1.2.1.0, Culture=neutral, processorArchitecture=MSIL", car elle a une dépendance indirecte sur l'assembly Framework "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" qui n'a pas été résolu dans le framework actuellement ciblé. ".NETFramework,Version=v4.0". Pour résoudre ce problème, supprimez la référence "StatsN, Version=1.2.1.0, Culture=neutral, processorArchitecture=MSIL" ou reciblez votre application vers une version de framework qui contient "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".	Goodyear.DataAccess	1			
`

etc.. (around 15 of them..)
Tried to remove the auto binding in app.config but did not change anything.

**Comment by TerribleDev** [comment]
I don't speak french so I can't read that error message in its entirety. This package uses [micorosft.bcl.async](https://www.nuget.org/packages/Microsoft.Bcl.Async/) which uses binding redirects to provide support for async/await on .net 4. However lots of legacy net4 apps can't use this package due to their architectures not allowing assembly binding redirect to work properly.

There is a [no async](https://www.nuget.org/packages/StatsN.NoAsync/) version of this client that does not include any async api, and also thus not include any assembly binding redirect. I'd suggest you start there, so long as you can tolerate the I/O being synchronous.

**Comment by TerribleDev** [comment]
@eagleamon is using the alternative package satisfactory?

**Comment by wookiesh** [comment]
Sorry, have not yet had time to try it as I am fiddling a bit with app.metrics for now.
Should be able to try next week, thanks for the answer btw!
